apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalogue-secrets
  labels:
    app: catalogue
    environment: dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: catalogue-secrets
    creationPolicy: Owner

    template:
      type: Opaque
      metadata:
        labels:
          app: catalogue
          environment: dev

      data:
        MONGODB_USERNAME: "{{ .mongodb_username }}"
        MONGODB_PASSWORD: "{{ .mongodb_password }}"
        MONGODB_DATABASE: "{{ .mongodb_database }}"
        MONGODB_URI: "{{ .mongodb_connection_string }}"
        FLASK_ENV: "{{ .flask_env }}"
        LOG_LEVEL: "{{ .log_level }}"
        DATA_SOURCE: "{{ .data_source }}"

  data:
    - secretKey: mongodb_username
      remoteRef:
        key: secret/data/craftista/dev/catalogue/mongodb-credentials
        property: username

    - secretKey: mongodb_password
      remoteRef:
        key: secret/data/craftista/dev/catalogue/mongodb-credentials
        property: password

    - secretKey: mongodb_database
      remoteRef:
        key: secret/data/craftista/dev/catalogue/mongodb-credentials
        property: database

    - secretKey: mongodb_connection_string
      remoteRef:
        key: secret/data/craftista/dev/catalogue/mongodb-uri
        property: connection_string

    - secretKey: flask_env
      remoteRef:
        key: secret/data/craftista/dev/catalogue/config
        property: flask_env

    - secretKey: log_level
      remoteRef:
        key: secret/data/craftista/dev/catalogue/config
        property: log_level

    - secretKey: data_source
      remoteRef:
        key: secret/data/craftista/dev/catalogue/config
        property: data_source
