apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recommendation-secrets
  labels:
    app: recommendation
    environment: dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: recommendation-secrets
    creationPolicy: Owner

    template:
      type: Opaque
      metadata:
        labels:
          app: recommendation
          environment: dev

      data:
        REDIS_PASSWORD: "{{ .redis_password }}"
        REDIS_URI: "{{ .redis_connection_string }}"
        REDIS_HOST: "{{ .redis_host }}"
        REDIS_PORT: "{{ .redis_port }}"
        ENVIRONMENT: "{{ .environment }}"
        LOG_LEVEL: "{{ .log_level }}"

  data:
    - secretKey: redis_password
      remoteRef:
        key: secret/data/craftista/dev/recommendation/redis-credentials
        property: password

    - secretKey: redis_connection_string
      remoteRef:
        key: secret/data/craftista/dev/recommendation/redis-uri
        property: connection_string

    - secretKey: redis_host
      remoteRef:
        key: secret/data/craftista/dev/recommendation/redis-uri
        property: host

    - secretKey: redis_port
      remoteRef:
        key: secret/data/craftista/dev/recommendation/redis-uri
        property: port

    - secretKey: environment
      remoteRef:
        key: secret/data/craftista/dev/recommendation/config
        property: environment

    - secretKey: log_level
      remoteRef:
        key: secret/data/craftista/dev/recommendation/config
        property: log_level
