apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: voting-secrets
  labels:
    app: voting
    environment: dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: voting-secrets
    creationPolicy: Owner

    template:
      type: Opaque
      metadata:
        labels:
          app: voting
          environment: dev

      data:
        POSTGRES_USERNAME: "{{ .postgres_username }}"
        POSTGRES_PASSWORD: "{{ .postgres_password }}"
        POSTGRES_DATABASE: "{{ .postgres_database }}"
        JDBC_URL: "{{ .jdbc_url }}"
        POSTGRES_URI: "{{ .postgres_connection_string }}"
        SPRING_DATASOURCE_URL: "{{ .jdbc_url }}"
        SPRING_DATASOURCE_USERNAME: "{{ .postgres_username }}"
        SPRING_DATASOURCE_PASSWORD: "{{ .postgres_password }}"
        SPRING_PROFILES_ACTIVE: "{{ .spring_profiles_active }}"
        LOG_LEVEL: "{{ .log_level }}"

  data:
    - secretKey: postgres_username
      remoteRef:
        key: secret/data/craftista/dev/voting/postgres-credentials
        property: username

    - secretKey: postgres_password
      remoteRef:
        key: secret/data/craftista/dev/voting/postgres-credentials
        property: password

    - secretKey: postgres_database
      remoteRef:
        key: secret/data/craftista/dev/voting/postgres-credentials
        property: database

    - secretKey: jdbc_url
      remoteRef:
        key: secret/data/craftista/dev/voting/postgres-uri
        property: jdbc_url

    - secretKey: postgres_connection_string
      remoteRef:
        key: secret/data/craftista/dev/voting/postgres-uri
        property: connection_string

    - secretKey: spring_profiles_active
      remoteRef:
        key: secret/data/craftista/dev/voting/config
        property: spring_profiles_active

    - secretKey: log_level
      remoteRef:
        key: secret/data/craftista/dev/voting/config
        property: log_level
