apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: craftista-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mongodb-credentials
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: secret/craftista/dev/catalogue/mongodb-credentials
        property: username
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: secret/craftista/dev/catalogue/mongodb-credentials
        property: password