apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  labels:
    app: cert-manager
    component: dns-solver
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: cert-manager
          component: cloudflare-credentials
      data:
        api-token: "{{ .api_token }}"
  data:
    - secretKey: api_token
      remoteRef:
        key: secret/data/craftista/homelab/cloudflare
        property: api-token