apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: craftista-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/craftista/staging/voting/postgres-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/craftista/staging/voting/postgres-credentials
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/craftista/staging/voting/postgres-credentials
        property: database
