apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://10.0.0.212:8200"
      caProvider:
        type: ConfigMap
        name: vault-ca
        key: ca.crt