# ArgoCD Installation Manifest
# This file references the official ArgoCD installation manifest
# Version: v2.9.3 (stable release)
#
# To install ArgoCD, apply this manifest after creating the namespace:
#   kubectl create namespace argocd
#   kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
#
# Or use the setup script: scripts/setup-argocd.sh
#
# For production deployments, consider using the HA (High Availability) manifest:
#   kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/ha/install.yaml
#
# Official installation documentation:
# https://argo-cd.readthedocs.io/en/stable/getting_started/

---
# NOTE: The actual ArgoCD installation manifest is quite large (5000+ lines)
# Instead of duplicating it here, we reference the official upstream manifest
# This ensures we always use the tested, official version
#
# The manifest includes:
# - CustomResourceDefinitions (Application, AppProject, ApplicationSet)
# - ServiceAccounts for all ArgoCD components
# - ClusterRoles and ClusterRoleBindings for RBAC
# - ConfigMaps for ArgoCD configuration
# - Secrets for TLS certificates and credentials
# - Services for argocd-server, argocd-repo-server, argocd-dex-server, argocd-redis
# - Deployments for all ArgoCD components
# - StatefulSet for Redis (if using built-in Redis)
#
# Apply the official manifest with:
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-installation-info
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: installation
data:
  version: "v2.9.3"
  manifest-url: "https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml"
  ha-manifest-url: "https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/ha/install.yaml"
  installation-command: |
    # Standard installation
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml

    # High Availability installation (recommended for production)
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/ha/install.yaml

  post-installation: |
    # Get the initial admin password
    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

    # Port forward to access the UI
    kubectl port-forward svc/argocd-server -n argocd 8080:443

    # Access the UI at https://localhost:8080
    # Username: admin
    # Password: (from the command above)

    # Install ArgoCD CLI
    # macOS: brew install argocd
    # Linux: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.9.3/argocd-linux-amd64

    # Login via CLI
    argocd login localhost:8080

    # Change admin password
    argocd account update-password
