apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Policy CSV format: p, subject, resource, action, object, effect
  # Role CSV format: g, subject, role

  # Default policy for all users
  # Options: role:readonly, role:admin, ""
  policy.default: role:readonly

  # RBAC Policy Rules
  # Format: p, <role/user/group>, <resource>, <action>, <object>, <effect>
  policy.csv: |
    # Admin role - full access to everything
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, get, *, allow
    p, role:admin, exec, create, */*, allow

    # Developer role - can manage applications in dev and staging
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, create, craftista-dev/*, allow
    p, role:developer, applications, create, craftista-staging/*, allow
    p, role:developer, applications, update, craftista-dev/*, allow
    p, role:developer, applications, update, craftista-staging/*, allow
    p, role:developer, applications, delete, craftista-dev/*, allow
    p, role:developer, applications, sync, craftista-dev/*, allow
    p, role:developer, applications, sync, craftista-staging/*, allow
    p, role:developer, applications, override, craftista-dev/*, allow
    p, role:developer, applications, override, craftista-staging/*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, projects, get, *, allow
    p, role:developer, logs, get, craftista-dev/*, allow
    p, role:developer, logs, get, craftista-staging/*, allow

    # DevOps role - can manage all applications but not cluster/repo config
    p, role:devops, applications, *, */*, allow
    p, role:devops, repositories, get, *, allow
    p, role:devops, projects, get, *, allow
    p, role:devops, clusters, get, *, allow
    p, role:devops, logs, get, *, allow
    p, role:devops, exec, create, */*, allow

    # Production deployer role - can only sync production applications
    p, role:prod-deployer, applications, get, */*, allow
    p, role:prod-deployer, applications, sync, craftista-prod/*, allow
    p, role:prod-deployer, logs, get, craftista-prod/*, allow
    p, role:prod-deployer, projects, get, *, allow

    # Readonly role - can only view applications
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, logs, get, */*, allow

    # CI/CD service account - can update applications and sync
    p, role:cicd, applications, get, */*, allow
    p, role:cicd, applications, update, */*, allow
    p, role:cicd, applications, sync, craftista-dev/*, allow
    p, role:cicd, applications, sync, craftista-staging/*, allow
    p, role:cicd, repositories, get, *, allow
    p, role:cicd, projects, get, *, allow

    # Monitoring role - can only view status and logs
    p, role:monitoring, applications, get, */*, allow
    p, role:monitoring, logs, get, */*, allow
    p, role:monitoring, projects, get, *, allow

    # Group mappings (for SSO integration)
    # Format: g, <user/group>, <role>

    # Map admin user to admin role
    g, admin, role:admin

    # Map developer account to developer role
    g, developer, role:developer

    # Map readonly account to readonly role
    g, readonly, role:readonly

    # GitHub team mappings (when using GitHub SSO)
    # g, your-github-org:platform-team, role:admin
    # g, your-github-org:developers, role:developer
    # g, your-github-org:devops, role:devops
    # g, your-github-org:readonly, role:readonly

    # Service account mappings
    # g, system:serviceaccount:argocd:argocd-application-controller, role:admin
    # g, system:serviceaccount:ci-cd:github-actions, role:cicd

  # Scopes for OIDC/SSO
  # Defines which OIDC claims map to ArgoCD groups
  scopes: "[groups, email]"

  # Policy matching mode
  # Options: glob, regex
  policy.matchMode: glob
