apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secrets
  labels:
    app: frontend
    environment: prod
spec:
  refreshInterval: 30m

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: frontend-secrets
    creationPolicy: Owner

    template:
      type: Opaque
      metadata:
        labels:
          app: frontend
          environment: prod

      data:
        SESSION_SECRET: "{{ .session_secret }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        NODE_ENV: "{{ .node_env }}"
        LOG_LEVEL: "{{ .log_level }}"
        PORT: "{{ .port }}"

  data:
    - secretKey: session_secret
      remoteRef:
        key: secret/data/craftista/prod/frontend/api-keys
        property: session_secret

    - secretKey: jwt_secret
      remoteRef:
        key: secret/data/craftista/prod/frontend/api-keys
        property: jwt_secret

    - secretKey: node_env
      remoteRef:
        key: secret/data/craftista/prod/frontend/config
        property: node_env

    - secretKey: log_level
      remoteRef:
        key: secret/data/craftista/prod/frontend/config
        property: log_level

    - secretKey: port
      remoteRef:
        key: secret/data/craftista/prod/frontend/config
        property: port
